### ISSUE TITLE
Using this gem with blocks

### ISSUE THREAD

**Issue by bcackerman** [n8/multi_fetch_fragments#25]
I'm a bit confused with the documentation.  Am I still able to use this gem with a cache block of code for example like this:

``` ruby
<% cache(['v1', @orders.count]) do %>
    <% if @orders.count < 1 %>
        <div class="row-fluid">
            ...
        </div>
    <% end %>
<% end %>
```

**Comment by n8** [comment]
The gem is just for rendering out a collection of partials using render :partial. So yes you should be able to still use a cache block like this without this gem interfering.
