### ISSUE TITLE
Works with Rails 4 Cache Digests?

### ISSUE THREAD

**Issue by thomasklemm** [n8/multi_fetch_fragments#5]
Hey,

this looks extremely nice. One theoretical question: Does `multi_fetch_fragments` also handle the new Rails 4 way of including a digest of the rendered template and it's dependencies into the cache key?

This behavior is abstracted for Rails 3.2 into the [Cache Digests](https://github.com/rails/cache_digests) gem as well.

Thanks for your answer in advance.

Best regards,
Thomas

**Comment by n8** [comment]
Hey Thomas,

Thanks for the note. No, unfortunately I don't think it's going to work as is. I just took a brief look at the Cache Digest. 

But it doesn't look impossible to alter this gem to generate fragment keys like Cache Digest does and make sure this stuff still works. 

-Nate

**Comment by PikachuEXE** [comment]
Cache Digest support would definitely makes this gem even better!!

Thanks for your work btw. :rose: 

Off Topic: [this page](http://ninjasandrobots.com/rails-faster-partial-rendering-and-caching) looks nicer to Github readme  
Maybe put the link into readme?

**Comment by PikachuEXE** [comment]
:thumbsup: 

You might want to state that the gem is compatible with Cache Digest

**Comment by thomasklemm** [comment]
Nice, thanks :-D
